export const AUTHENTICATED = 'USER_AUTHENTICATED';
export const UNAUTHENTICATED = "USER_UNAUTHENTICATED";
export const REQUIRES_AUTHENTICATION = "USER_AUTHENTICATION_REQUIRED";
export const AUTH_ERROR = 'AUTH_ERROR';

export const JOINED_ROOM = "JOINED_ROOM";
export const REFRESHED_LOBBY = "REFRESHED_LOBBY";
export const REFRESHED_ROOM = "REFRESHED_ROOM";
export const GAME_ERROR = "GAME_ERROR";
export const GAME_FORFEITED = "GAME_FORFEITED";